###

POST http://localhost:4000/sign-up/customer
Content-Type: application/json

{
    "email": "agnes@gmail.com",
    "authType": "native",
    "name": "Agnes",
    "password": "password",
    "profilePicture": "www.google.com"
}