INSERT INTO toilets values(1, 2, 'AMK Bus Interchange', 'Central', '53 Ang Mo Kio Avenue 3, S(569933)', 100, 150, NULL, 5);
INSERT INTO toilet_certifications values(1, 'Restroom Association (Singapore)', 4);
INSERT INTO toilet_features values(1, True, False, True, True, False, True, True, False, False, False);
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_1.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_2.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_3.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_4.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_5.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_6.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_7.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_8.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_9.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_10.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_11.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_12.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_13.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_14.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_15.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_16.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_17.jpg');
INSERT INTO toilet_images values(1, 'https://toilet.org.sg/photos/4S_BusInterchangeAMK_18.jpg');
